# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TeamsBots

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are initialized and updated

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: testbotapp.azurecr.io
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_5B6A81BC05844BF78238C19AD4408B23 }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_5A904DA0AD2E4D1DA7162EC58F484963 }}

    - name: Build and push container image to ACR
      run: |
        docker buildx build --file ./Dockerfile --tag testbotapp.azurecr.io/appsvc/staticsite:${{ github.sha }} --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'MicrosoftAppId'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TeamBots'
        slot-name: 'MicrosoftAppId'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FBBAEF05326B491F8F0796438BA09B6E }}
        images: 'testbotapp.azurecr.io/appsvc/staticsite:${{ github.sha }}' 
