# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TeamsBots

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are initialized and updated

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: testbotapp.azurecr.io
        username: TestBotApp
        password: /D83b5n8VDf43wngr9XCCT1M0oFeyZSqD/oXC6c3Nj+ACRCFmZry

    - name: Build and push container image to ACR
      run: |
        /usr/bin/docker buildx build --file ./Dockerfile --iidfile /tmp/docker-build-push-QcNBwb/iidfile --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-QcNBwb/tmp-2434-6HfXnbnN86RA --tag testbotapp.azurecr.io/appsvc/staticsite:${{ github.sha }} --metadata-file /tmp/docker-build-push-QcNBwb/metadata-file --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TeamsBots'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        images: 'testbotapp.azurecr.io/appsvc/staticsite:${{ github.sha }}'
